# Generated by Django 5.1.5 on 2025-02-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=150, unique=True)),
                ('title', models.TextField()),
            ],
        ),
    ]
