# Generated by Django 5.1.5 on 2025-02-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_model',
            new_name='Products_M',
        ),
    ]
